### ISSUE TITLE
Compilation warnings encountered

### ISSUE THREAD

**Issue by Janaka-Steph** [Dexaran/ERC23-tokens#12]
Hello,

```
Compilation warnings encountered:

ERC223_Token.sol:91:23: : Unused local variable
  function isContract(address _addr) private returns (bool is_contract) {
                      ^-----------^
```

**Comment by Dexaran** [comment]
Nevermind.
`_addr` is used inside the inline assembly code fragment so compiler is complaining about it.
It is not really an unused variable since it is used here:
https://github.com/Dexaran/ERC23-tokens/blob/Recommended/ERC223_Token.sol#L95

**Comment by Janaka-Steph** [comment]
We have to tell the compiler then :-)  Ok I close it.
