### ISSUE TITLE
Add check for x == 0 in safeMul

### ISSUE THREAD

**Issue by CoenKuij** [Dexaran/ERC23-tokens#6]
Why isn't there a check in safeMul for x ==0, the same way there is a check for y==0?

**Comment by Dexaran** [comment]
I'm not the developer of SafeMath. I've just implemented their default functions as-is. This is not related to the token standard, but you can create an issue related to SafeMath structure here: https://github.com/LykkeCity/EthereumApiDotNetCore/blob/master/src/ContractBuilder/contracts/token/SafeMath.sol

P.S. The ERC223 standard is not relying on `safeMul ` function behavior.
